"""empty message

Revision ID: 1bf44cc41a8c
Revises: 
Create Date: 2025-10-01 21:24:53.356169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf44cc41a8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary',
    sa.Column('id_word', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=120), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('points_per_word', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_word'),
    sa.UniqueConstraint('word')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('game',
    sa.Column('id_game', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('correct_words', sa.Integer(), nullable=False),
    sa.Column('failed_words', sa.Integer(), nullable=False),
    sa.Column('average_precision', sa.Float(), nullable=False),
    sa.Column('wpm_average', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_game')
    )
    op.create_table('game_words',
    sa.Column('id_game', sa.Integer(), nullable=False),
    sa.Column('id_word', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_game'], ['game.id_game'], ),
    sa.ForeignKeyConstraint(['id_word'], ['dictionary.id_word'], ),
    sa.PrimaryKeyConstraint('id_game', 'id_word')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_words')
    op.drop_table('game')
    op.drop_table('user')
    op.drop_table('dictionary')
    # ### end Alembic commands ###
